#!/usr/bin/with-contenv sh
set -e
umask "${UMASK:-022}"

export HOME="/config"

[ -f /run/config/fetchmailrc ] || { echo "missing /run/config/fetchmailrc"; exit 1; }

mkdir -p /run/fetchmail
chown abc:abc /run/fetchmail

: "${ADHD_POLL_INTERVAL:=300}";

exec s6-setuidgid abc \
  env HOME="/config" \
  fetchmail --nodetach \
            --pidfile /run/fetchmail/fetchmail.pid \
            --idfile /config/.fetchids \
            --daemon $ADHD_POLL_INTERVAL \
            -f /run/config/fetchmailrc
