#!/usr/bin/with-contenv sh
set -e

: "${PUID:=1000}"
: "${PGID:=1000}"

if [ ! -f /config/.netrc ]; then
    echo "No /config/.netrc found. Creating empty."
    touch /config/.netrc
fi

chmod 600 /config/.netrc || true
chown "$PUID:$PGID" /config/.netrc || true
